---
name: Sample Workflow
on:
  push:
    branches: -main
  workflow_dispatch: null
jobs: 
  cohort16-job:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Make a directory
        run: mkdir gun
      - name: Set ENV variables
        env: null
        COHORTID: "16"
        LOCATION: CALGARY
        run: -echo "$COHORTID, $LOCATION"
      - name: Set output message
        env: null
        COHORTID: "16"
        LOCATION: CALGARY
        id: output_step
        run: echo "::set-output name=custom_message::Hello, to Cohort $CohortID students
          in $Location"
      - name: Use output message
        run: echo "The custom message is; ${{ steps.output_step.outputs.custom_message
          }}"
